---
  - name: Ensures /srv/docker/registry dir exists
    become: true
    file: path=/srv/docker/registry/ state=directory

  - name: Pull docker registry image
    docker_image:
      name: registry:2

  - name: Run the docker registry container
    docker_container:
      name: docker-registry
      image: registry:2
      state: started
      volumes:
        - /srv/docker/registry:/var/lib/registry
      ports:
        - "5000:5000"
