---
language: 'python'
python: '2.7'

sudo: required

env:
  - SITE_AND_INVENTORY='tests/test_on_travis.yml -i tests/inventory'

install:
  - 'pip install ansible'
  - 'printf "[defaults]\nroles_path = ../" > ansible.cfg'

script:
  - 'ansible-playbook $SITE_AND_INVENTORY --syntax-check'
  - 'ansible-playbook $SITE_AND_INVENTORY --connection=local -vvvv'
  - '/usr/local/go/bin/go version'

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
