---
  - name: Update apt cache
    become: true
    apt:
      update_cache: yes

  - name: Install haproxy
    become: true
    apt:
      name: haproxy
      state: present

  - name: Copy configuration file
    copy:
      src: haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg

  - name: Restart haproxy
    service: name=haproxy.service state=reloaded enabled=yes
