---
galaxy_info:
  author: Gennady Trafimenkov
  description: Install golang
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
    - name: CentOS
    - name: GenericLinux
  categories:
    - golang

  issue_tracker_url: https://github.com/gtrafimenkov/ansible-role-golang/issues

dependencies: []
